{are    [[:pairs 2]]
 case   [[:pairs 1]]
 catch  [[:always-body 3]]
 cond   [[:pairs 0]]
 cond-> [[:pairs 0]]
 cond->> [[:pairs 0]]
 condp  [[:pairs 2]]
 def    [[:defn]]
 defmacro [[:defn]]
 defn   [[:defn]]
 defn-  [[:defn]]
 defonce [[:defn]]
 defprotocol [[:defn]]
 defrecord [[:defn]]
 deftype [[:defn]]
 delay  [[:always-body 1]]
 do     [[:always-body 1]]
 finally [[:always-body 1]]
 future [[:always-body 1]]
 go     [[:always-body 1]]
 go-loop [[:always-body 2]]
 if     [[:consistent 1]]
 if-let [[:consistent 1]]
 if-not [[:consistent 1]]
 if-some [[:consistent 1]]
 let    [[:pairs 0 :inner] [:always-body]]
 letfn  [[:pairs 0 :inner] [:always-body]]
 locking [[:always-body 2]]
 loop   [[:always-body 2]]
 ns     [[:ns]]
 try    [[:always-body 1]]
 when   [[:consistent 1]]
 when-first [[:consistent 1]]
 when-let [[:consistent 1]]
 when-not [[:consistent 1]]
 when-some [[:consistent 1]]
 with-local-vars [[:always-body 2]]
 with-open [[:always-body 2]]
 with-out-str [[:always-body 1]]
 with-redefs [[:always-body 2]]}
